export const API_URL = import.meta.env.VITE_API_URL;
export const PAGE_SIZE = 5;

export const USER_ROLES = {
  user: { color: "silver", label: "Utilisateurice", roles: ["user"] },
  contributor: {
    color: "yellow",
    label: "Contributeurice",
    roles: ["user", "contributor"],
  },
  admin: {
    color: "blue",
    label: "Administrateurice",
    roles: ["user", "contributor", "admin"],
  },
};

export const PRODUCT_STATES = {
  CREATED: { color: "grey", label: "À vérifier", role: "user" },
  NOT_FOUND: { color: "silver", label: "Inconnu", role: "contributor" },
  NEED_CONTACT: { color: "yellow", label: "À contacter", role: "contributor" },
  WAITING_BRAND_REPLY: {
    color: "blue",
    label: "Contacté",
    role: "contributor",
  },
  WAITING_PUBLISH: {
    color: "indigo",
    label: "À publier",
    role: "contributor",
  },
  PUBLISHED: { color: "green", label: "Publié", role: "admin" },
};

export const PRODUCT_STATUSES = {
  NOT_FOUND: { color: "silver", label: "Inconnu" },
  MAYBE_VEGAN: { color: "yellow", label: "Maybe vegan" },
  VEGAN: { color: "green", label: "Vegan" },
  NON_VEGAN: { color: "red", label: "Non vegan" },
};

export const ADDITIVES_STATUSES = {
  V: { color: "green", label: "Vegan" },
  C: { color: "red", label: "Carniste" },
  D: { color: "yellow", label: "Ça dépend" },
  U: { color: "silver", label: "Inconnu" },
};
/** Used to highlight ingredients in product detail view */
export const NON_VEGAN_INGREDIENTS = [
  "egg",
  "oeuf",
  "milk",
  "lait",
  "lactose",
  "lactoserum",
  "lactosérum",
  "cheese",
  "fromage",
  "emmental",
  "butter",
  "beurre",
  "cream",
  "crème",
  "creme",
  "caseine",
  "caséine",
  "gelatine",
  "gélatine",
  "fish",
  "poisson",
  "meet",
  "viande",
  "beef",
  "boeuf",
  "chicken",
  "poulet",
  "bacon",
  "pork",
  "porc",
  "viel",
  "veau",
  "animal fat",
  "graisse animale",
  "animal lecithin",
  "lécithine animale",
  "rennet",
  "présure",
  "crustacés",
  "crustaces",
  "crustaceans",
  "mollusc",
  "mollusque",
  "cochenille",
  "honey",
  "miel",
  "cire d'abeille",
  "beeswax",
  "propolis",
  "collagen",
  "collagène",
  "collagene",
  "additives",
  "additifs",
  "natural flavour",
  "arôme naturel",
  "vitamin d",
  "vitamine d",
];
/**
 * Used to highlight ingredients in product detail view
 *
 * Array build from e_numbers database
 */
export const NON_VEGAN_E_NUMBERS = [
  "E170",
  "E621",
  "E628",
  "E633",
  "E1105",
  "E441",
  "E542",
  "E901",
  "E904",
  "E910",
  "E913",
  "E920",
  "E921",
  "E966",
  "E161g",
  "E161h",
  "E161i",
  "E161j",
  "E252",
  "E270",
  "E322",
  "E325",
  "E326",
  "E327",
  "E422",
  "E430",
  "E431",
  "E432",
  "E433",
  "E434",
  "E435",
  "E436",
  "E442",
  "E470a",
  "E470b",
  "E471",
  "E472a",
  "E472b",
  "E472c",
  "E472d",
  "E472e",
  "E472f",
  "E473",
  "E474",
  "E475",
  "E476",
  "E477",
  "E478",
  "E479b",
  "E481",
  "E482",
  "E483",
  "E491",
  "E492",
  "E493",
  "E494",
  "E495",
  "E570",
  "E572",
  "E585",
  "E627",
  "E631",
  "E635",
  "E640",
  "E120",
];
